import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { BodyContents } from './components/body-portals'
import { PickOnTopContent } from './components/pick-on-top/pick-on-top-content'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <PickOnTopContent>
          <BodyContents>
            {children}
          </BodyContents>
        </PickOnTopContent>
      </body>
    </html>
  )
}
