import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { DarMode } from './dark-mode'
import { Menu } from './menu'
import { LayoutContent } from './layout-contecnt'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutContent>
          {children}
        </LayoutContent>
      </body>
    </html>
  )
}
